spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@172.16.100.55:1521:soarcx
    username: hz_fzyj
    password: VZAA3PFC

logging:
  level:
    root: info
    com.hzfc.management: info
